# Generated by Django 4.0.2 on 2022-03-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Toy', 'Toy'), ('Electronic', 'Electronic'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Kitchen', 'Kitchen')], max_length=20),
        ),
    ]
