# Generated by Django 4.0.2 on 2022-03-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='time',
        ),
    ]
