# Generated by Django 4.0.2 on 2022-03-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_watchlist_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
